# Generated by Django 2.1.2 on 2018-12-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 initial = True

 dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

 operations = [
    migrations.CreateModel(
        name='MeetingRecord',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('date', models.DateField()),
            ('time', models.TimeField()),
            ('cost_time', models.IntegerField()),
            ('place', models.CharField(max_length=50)),
            ('theme', models.TextField()),
            ('theme_content', models.TextField()),
            ('remark', models.TextField(null=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ],
    ),
    migrations.CreateModel(
        name='Plan',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('type', models.CharField(max_length=32)),
            ('plan_name', models.CharField(max_length=32)),
            ('plan_result', models.TextField()),
            ('is_reviewed', models.BooleanField()),
            ('head_person', models.CharField(max_length=32)),
            ('affiliated_person', models.TextField()),
            ('planed_time', models.IntegerField()),
            ('planed_start_time', models.DateField()),
            ('planed_end_time', models.DateField()),
            ('actual_time', models.IntegerField(null=True)),
            ('actual_start_time', models.DateField(null=True)),
            ('actual_end_time', models.DateField(null=True)),
            ('advanced_postponed_time', models.IntegerField()),
            ('remark', models.TextField()),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ],
    ),
    migrations.CreateModel(
        name='Target',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('term', models.TextField()),
            ('time', models.DateField()),
            ('expected_result', models.TextField()),
            ('time_consumed', models.TextField()),
            ('content', models.TextField()),
            ('end_of_term_summary', models.TextField()),
            ('semester', models.TextField(null=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ],
    ),
    migrations.CreateModel(
        name='WeeklySummary',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('week', models.IntegerField(default=0)),
            ('submit_time', models.DateTimeField(auto_now=True)),
            ('average_work_hour', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ('absent_hour', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ('real_name', models.CharField(max_length=150)),
            ('this_week_task', models.TextField()),
            ('next_week_task', models.TextField()),
            ('is_present', models.BooleanField(default=False)),
            ('is_absent', models.BooleanField(default=False)),
            ('is_left', models.BooleanField(default=False)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ],
    ),
    migrations.CreateModel(
        name='WorkSummary',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('date', models.DateTimeField()),
            ('type', models.CharField(max_length=32)),
            ('summary', models.TextField()),
            ('average_time', models.CharField(max_length=32)),
            ('all_days', models.IntegerField()),
            ('man_day', models.TextField(null=True)),
            ('natural_day', models.TextField(null=True)),
            ('remark', models.TextField(null=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ],
    ),
]