# Generated by Django 2.1.1 on 2018-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weekly_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=150)),
                ('this_week_task', models.TextField()),
                ('next_week_task', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
