# Generated by Django 2.1.1 on 2018-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_summary',
            name='weeek',
            field=models.IntegerField(default=0),
        ),
    ]
