# Generated by Django 2.1.1 on 2018-09-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_summary', '0002_weekly_summary_weeek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekly_summary',
            old_name='weeek',
            new_name='week',
        ),
    ]
