# Generated by Django 2.1.1 on 2018-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_summary', '0003_auto_20180915_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_summary',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekly_summary',
            name='is_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekly_summary',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
