# Generated by Django 2.1.1 on 2018-09-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_summary', '0004_auto_20180915_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weekly_summary',
        ),
    ]
