# Generated by Django 2.1.1 on 2018-09-14 16:09

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import django.utils.translation
import user_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('password', models.CharField(max_length=128)),
                ('real_name', models.CharField(blank=True, max_length=30, verbose_name=django.utils.translation.gettext)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False, verbose_name='permission')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', user_info.models.UserManager()),
            ],
        ),
    ]
