# Generated by Django 2.1.2 on 2018-12-17 13:50

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('current_user', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('real_name', models.CharField(blank=True, max_length=30)),
                ('is_student', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_display_all', models.BooleanField(blank=True, default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.TextField(blank=True)),
                ('nationality', models.TextField(blank=True)),
                ('born_in', models.TextField(blank=True)),
                ('id_number', models.TextField(blank=True)),
                ('student_id', models.TextField(blank=True)),
                ('entrance_time', models.TextField(blank=True)),
                ('graduate_time', models.TextField(blank=True)),
                ('major', models.TextField(blank=True)),
                ('group_name', models.TextField(blank=True)),
                ('tutor', models.TextField(blank=True)),
                ('bank_name', models.TextField(blank=True)),
                ('bank_id', models.TextField(blank=True)),
                ('phone_number', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('past_school', models.TextField(blank=True)),
                ('past_unit', models.TextField(blank=True)),
                ('thesis_defense_score', models.TextField(blank=True)),
                ('degree_paper', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', user_info.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('model', models.TextField()),
                ('manufacturer', models.TextField()),
                ('number', models.TextField()),
                ('parameter', models.TextField()),
                ('buying_date', models.DateField()),
                ('storing_place', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('teacher_name', models.TextField()),
                ('week_start', models.IntegerField()),
                ('week_end', models.IntegerField()),
                ('day', models.IntegerField()),
                ('class_number', models.IntegerField()),
                ('class_location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
