# Generated by Django 2.1.1 on 2018-09-19 17:09

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20180919_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='is_advanced',
            new_name='advanced_postponed_time',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_postponed',
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=30, verbose_name=django.utils.translation.gettext),
        ),
    ]
