# Generated by Django 2.1.1 on 2018-09-19 17:16

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20180920_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='advanced_postponed_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=30, verbose_name=django.utils.translation.gettext),
        ),
    ]
