# Generated by Django 2.1 on 2018-09-18 12:49

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20180918_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrecord',
            name='number',
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=30, verbose_name=django.utils.translation.gettext),
        ),
    ]
