# Generated by Django 2.1.1 on 2018-09-20 01:11

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_auto_20180920_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekly_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=150)),
                ('this_week_task', models.TextField()),
                ('next_week_task', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('week', models.IntegerField(default=0)),
                ('is_present', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_left', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=30, verbose_name=django.utils.translation.gettext),
        ),
    ]
