from django.db import models
from django.utils.timezone import now

# Create your models here.
class UploadRecord(models.Model):
    user_name = models.TextField(default="")
    username = models.TextField(default="")
    file_name = models.TextField(default="")
    upload_time = models.DateTimeField()
    group_name = models.TextField(default="")

class DailyReport(models.Model):
    username = models.TextField()
    real_name = models.TextField()
    fill_time = models.DateTimeField(default=now)
    date = models.DateField()
    today_1_name = models.TextField(default="")
    today_1_day = models.TextField(default="")
    today_1_quantitative = models.TextField(default="")
    today_1_qualitative = models.TextField(default="")
    today_2_name = models.TextField(default="")
    today_2_day = models.TextField(default="")
    today_2_quantitative = models.TextField(default="")
    today_2_qualitative = models.TextField(default="")
    today_3_name = models.TextField(default="")
    today_3_day = models.TextField(default="")
    today_3_quantitative = models.TextField(default="")
    today_3_qualitative = models.TextField(default="")
    today_4_name = models.TextField(default="")
    today_4_day = models.TextField(default="")
    today_4_quantitative = models.TextField(default="")
    today_4_qualitative = models.TextField(default="")
    today_5_name = models.TextField(default="")
    today_5_day = models.TextField(default="")
    today_5_quantitative = models.TextField(default="")
    today_5_qualitative = models.TextField(default="")
    tomorrow_1_name = models.TextField(default="")
    tomorrow_1_day = models.TextField(default="")
    tomorrow_1_quantitative = models.TextField(default="")
    tomorrow_1_qualitative = models.TextField(default="")
    tomorrow_2_name = models.TextField(default="")
    tomorrow_2_day = models.TextField(default="")
    tomorrow_2_quantitative = models.TextField(default="")
    tomorrow_2_qualitative = models.TextField(default="")
    tomorrow_3_name = models.TextField(default="")
    tomorrow_3_day = models.TextField(default="")
    tomorrow_3_quantitative = models.TextField(default="")
    tomorrow_3_qualitative = models.TextField(default="")
    tomorrow_4_name = models.TextField(default="")
    tomorrow_4_day = models.TextField(default="")
    tomorrow_4_quantitative = models.TextField(default="")
    tomorrow_4_qualitative = models.TextField(default="")
    tomorrow_5_name = models.TextField(default="")
    tomorrow_5_day = models.TextField(default="")
    tomorrow_5_quantitative = models.TextField(default="")
    tomorrow_5_qualitative = models.TextField(default="")
